-- =============================================================================
-- Biscuits IA — Seed backlog Adherents (BDD / Backend / Frontend / Import-Export)
-- Compatible avec public.tasks (task_management_full.sql)
-- =============================================================================

-- 1) Sprint/backlog de reference (idempotent)
INSERT INTO public.sprints (
  name,
  goal,
  start_date,
  end_date,
  status,
  velocity_target,
  velocity_actual
)
SELECT
  'Backlog Adherents V1',
  'Structurer et livrer le module adherents de bout en bout',
  CURRENT_DATE,
  CURRENT_DATE + INTERVAL '30 days',
  'active',
  55,
  0
WHERE NOT EXISTS (
  SELECT 1 FROM public.sprints WHERE name = 'Backlog Adherents V1'
);

-- 2) Taches
WITH sprint_ref AS (
  SELECT id
  FROM public.sprints
  WHERE name = 'Backlog Adherents V1'
  ORDER BY created_at DESC
  LIMIT 1
)
INSERT INTO public.tasks (
  title,
  description,
  corps,
  task_type,
  priority,
  status,
  sprint_id,
  story_points,
  time_estimate_hours,
  time_spent_hours,
  acceptance_criteria,
  deliverables,
  definition_of_done,
  dod_completed,
  tags,
  blocked_reason,
  doc_link,
  figma_link
)
SELECT *
FROM (
  VALUES
    -- ==============================
    -- Base de donnees
    -- ==============================
    (
      'Creer la table adherents',
      'Definir la structure adherents avec id, nom, prenom, email unique RFC 5322, telephone, adresse, date_adhesion, statut enum et tags.',
      'DB'::corps_type,
      'modeling'::task_type_enum,
      'P0'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      5,
      8.0,
      0.0,
      ARRAY['Schema cree', 'Contraintes principales posees', 'Compatibilite migration validee'],
      ARRAY['Table public.adherents'],
      ARRAY['Code revu', 'Documentation mise a jour'],
      ARRAY[false, false],
      ARRAY['adherents', 'schema', 'db'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Creer la table adherent_historiques',
      'Stocker les modifications de fiches adherents: champ_modifie, ancienne_valeur, nouvelle_valeur, timestamp, utilisateur_id.',
      'DB'::corps_type,
      'migration'::task_type_enum,
      'P1'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      3,
      5.0,
      0.0,
      ARRAY['Table historiques creee', 'FK adherent_id validee', 'Index de lecture poses'],
      ARRAY['Table public.adherent_historiques'],
      ARRAY['Code revu', 'Documentation mise a jour'],
      ARRAY[false, false],
      ARRAY['audit', 'adherents', 'db'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Creer les tables groupes et adherent_groupes',
      'Permettre la creation de groupes et leur association aux adherents via table de liaison.',
      'DB'::corps_type,
      'modeling'::task_type_enum,
      'P1'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      3,
      5.0,
      0.0,
      ARRAY['Table groupes creee', 'Table de liaison creee', 'Unicite des associations assuree'],
      ARRAY['Tables public.groupes, public.adherent_groupes'],
      ARRAY['Code revu', 'Documentation mise a jour'],
      ARRAY[false, false],
      ARRAY['groupes', 'many-to-many', 'db'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Creer les tables roles et utilisateur_roles',
      'Definir les roles admin, tresorier, lecture seule et leur association aux utilisateurs (RBAC).',
      'DB'::corps_type,
      'modeling'::task_type_enum,
      'P0'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      3,
      4.0,
      0.0,
      ARRAY['Roles semes', 'Table utilisateur_roles operationnelle', 'Contraintes d integrite posees'],
      ARRAY['Tables roles et utilisateur_roles'],
      ARRAY['Code revu', 'Documentation mise a jour'],
      ARRAY[false, false],
      ARRAY['rbac', 'permissions', 'db'],
      NULL,
      NULL,
      NULL
    ),

    -- ==============================
    -- Backend (FastAPI / Django)
    -- ==============================
    (
      'Implementer API CRUD adherents',
      'Creer GET /adherents, POST /adherents, PUT /adherents/{id}, DELETE /adherents/{id}.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P0'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      8,
      12.0,
      0.0,
      ARRAY['CRUD complet repond', 'Codes HTTP corrects', 'Erreurs metier gerees'],
      ARRAY['Controllers/Views CRUD adherents'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['api', 'crud', 'adherents'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Valider emails et telephones cote serveur',
      'Appliquer validation stricte RFC 5322 pour email et regles telephone dans les endpoints.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P0'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      5,
      7.0,
      0.0,
      ARRAY['Validation RFC 5322 active', 'Validation telephone active', 'Messages d erreur explicites'],
      ARRAY['Schemas de validation backend'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['validation', 'email', 'telephone'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Creer endpoint historique adherent',
      'Permettre GET /adherents/{id}/historique pour consulter les changements.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P1'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      3,
      4.0,
      0.0,
      ARRAY['Endpoint retourne l historique trie', 'Pagination optionnelle'],
      ARRAY['Endpoint GET /adherents/{id}/historique'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['api', 'historique', 'audit'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Implementer endpoints groupes',
      'Creer POST /groupes et GET /groupes/{id}/adherents pour gerer les groupes et leurs membres.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P1'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      5,
      7.0,
      0.0,
      ARRAY['Creation groupe OK', 'Lecture membres groupe OK'],
      ARRAY['Endpoints groupes'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['api', 'groupes', 'adherents'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Mettre en place RBAC backend',
      'Restreindre les endpoints selon roles via middleware/decorateurs.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P0'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      8,
      10.0,
      0.0,
      ARRAY['Matrice des droits appliquee', 'Routes protegees'],
      ARRAY['Middleware/decorateurs RBAC'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['security', 'rbac', 'backend'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Creer endpoint recherche et filtres adherents',
      'Implementer GET /adherents/search avec full-text et filtres statut/date/groupes.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P1'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      8,
      11.0,
      0.0,
      ARRAY['Recherche full-text rapide', 'Filtres combinables', 'Pagination stable'],
      ARRAY['Endpoint GET /adherents/search'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['search', 'filters', 'api'],
      NULL,
      NULL,
      NULL
    ),

    -- ==============================
    -- Frontend (Next.js)
    -- ==============================
    (
      'Creer formulaire reactif adherents',
      'Developper un formulaire ajout/modification adherent avec validation cote client.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P1'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      5,
      8.0,
      0.0,
      ARRAY['Formulaire reactif', 'Validation client visible', 'Gestion erreurs API'],
      ARRAY['Ecran formulaire adherent'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['frontend', 'nextjs', 'form'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Afficher liste paginee des adherents',
      'Implementer interface avec tri et filtres statut/date/groupes.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P1'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      8,
      10.0,
      0.0,
      ARRAY['Pagination fonctionnelle', 'Tri stable', 'Filtres relies API'],
      ARRAY['Ecran liste adherents'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['frontend', 'pagination', 'filters'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Ajouter barre de recherche full-text frontend',
      'Permettre recherche en temps reel avec suggestions sur les adherents.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P2'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      5,
      7.0,
      0.0,
      ARRAY['Recherche live', 'Debounce actif', 'Suggestions pertinentes'],
      ARRAY['Composant barre de recherche'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['frontend', 'search', 'ux'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Afficher historique des modifications adherent',
      'Creer interface de visualisation de l historique d un adherent.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P2'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      3,
      5.0,
      0.0,
      ARRAY['Timeline lisible', 'Pagination/horaire coherent'],
      ARRAY['Ecran historique adherent'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['frontend', 'historique', 'audit'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Gerer groupes via interface frontend',
      'Permettre creation/suppression de groupes et gestion des membres.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P2'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      5,
      8.0,
      0.0,
      ARRAY['CRUD groupes en UI', 'Association adherents-groupes en UI'],
      ARRAY['Ecrans groupes et membres'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['frontend', 'groupes', 'gestion'],
      NULL,
      NULL,
      NULL
    ),

    -- ==============================
    -- Import / Export
    -- ==============================
    (
      'Creer endpoint import adherents',
      'Developper POST /adherents/import pour importer depuis CSV/Excel.',
      'DEV'::corps_type,
      'etl_pipeline'::task_type_enum,
      'P1'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      5,
      7.0,
      0.0,
      ARRAY['CSV supporte', 'Excel supporte', 'Validation des colonnes'],
      ARRAY['Endpoint POST /adherents/import'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['import', 'csv', 'excel'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Creer endpoint export adherents',
      'Developper GET /adherents/export pour exporter en CSV/Excel.',
      'DEV'::corps_type,
      'etl_pipeline'::task_type_enum,
      'P1'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      3,
      5.0,
      0.0,
      ARRAY['CSV genere', 'Excel genere', 'Encodage valide'],
      ARRAY['Endpoint GET /adherents/export'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['export', 'csv', 'excel'],
      NULL,
      NULL,
      NULL
    ),
    (
      'Ajouter formulaire import et bouton export en frontend',
      'Integrer mapping colonnes pour import et bouton export dans l interface.',
      'DEV'::corps_type,
      'feature'::task_type_enum,
      'P2'::priority_level,
      'todo'::task_status,
      (SELECT id FROM sprint_ref),
      5,
      7.0,
      0.0,
      ARRAY['Formulaire import operationnel', 'Mapping colonnes operationnel', 'Export declenchable depuis UI'],
      ARRAY['UI import/export adherents'],
      ARRAY['Code revu', 'Tests passants'],
      ARRAY[false, false],
      ARRAY['frontend', 'import-export', 'ux'],
      NULL,
      NULL,
      NULL
    )
) AS backlog_tasks (
  title,
  description,
  corps,
  task_type,
  priority,
  status,
  sprint_id,
  story_points,
  time_estimate_hours,
  time_spent_hours,
  acceptance_criteria,
  deliverables,
  definition_of_done,
  dod_completed,
  tags,
  blocked_reason,
  doc_link,
  figma_link
)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.tasks t
  WHERE t.title = backlog_tasks.title
);
