const fs = require('fs');
const p1 = 'src/pages/api/groupes/index.ts';
let s1 = fs.readFileSync(p1, 'utf8');
const old = "  const { rateLimitResponse } = flat;\r\n  if (!flat.ok) return jsonError('Non autorise.', flat.status);\r\n  const { ctx } = flat;\r\n  if (rateLimitResponse) return rateLimitResponse;";
const newB = "  if (!flat.ok) return jsonError('Non autorise.', flat.status);\r\n  const { ctx, rateLimitResponse } = flat;\r\n  if (rateLimitResponse) return rateLimitResponse;";
const count = s1.split(old).length - 1;
console.log('matches GET:', count);
s1 = s1.split(old).join(newB);
fs.writeFileSync(p1, s1, 'utf8');
console.log('OK h10b');
